import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Component/NavBar";
import siteConfig from "./../../public/data/siteconfig.json";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navData = siteConfig.data.attributes.navItems;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavBar {...navData}/>
        {children}
      </body>
    </html>
  );
}
