import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/ui/NavBar";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col mt-auto`}>
        <NavBar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
