name: Cypress E2E Tests

on:
  push:
    branches:
      - dev
      - stage
      - prod
  pull_request:
    branches:
      - dev
      - stage
      - prod

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3

      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: npm install

      - name: Clone Backend Repository
        run: |
          git clone https://github.com/kb21-rw/experience-rwanda-backend.git backend
          chmod -R 777 backend

      - name: Install Backend Dependencies
        working-directory: backend
        run: yarn

      - name: Start Backend Server
        working-directory: backend
        run: yarn dev &

      - name: Start Frontend Server
        run: npm run dev &

      - name: Wait for Backend Server to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: 'http://localhost:3000'  
          timeout: 60

      - name: Wait for Frontend Server to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: 'http://localhost:3000'  
          timeout: 60

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          browser: chrome
